### ISSUE TITLE
ColorfullButton中有个会引起crach的问题

### ISSUE THREAD

**Issue by LeonQi0317** [keshiim/ZMJImageEditor#2]
`for (CALayer *layer in self.layer.sublayers) {
            [layer removeFromSuperlayer];
    }`
集成sdk后会报找不到父layer的错误，引发的对象是UIButtonLabel，没有分析出原因。
目前removeFromSuperlayer之前判断一下layer的hidden属性可以规避这一问题。

**Comment by keshiim** [comment]
多谢，我修改后，提交一下
