### ISSUE TITLE
你好，我发现BUG

### ISSUE THREAD

**Issue by 542604974** [keshiim/ZMJImageEditor#3]
跳转到ZMJImageEditor页面右边有条黑边，需要点击一下才会隐藏，编辑文字，第一次编辑后，第二次编辑没有把第一次编辑的内容传到编辑页面，导致第二次编辑的会加上第一次编辑的内容，第一次打开红色圆点没有点击状态

**Comment by keshiim** [comment]
@542604974 Hi，你好
 你上述的问题中，只有第一次代开红色圈不会是默认点击状态存在，这个不默认开启红色是后来交互起来略有怪异，所以不设为默认红色。你说的前两个问题，可能是你的功能中配置不对，或者使用不当。还望参考

**Comment by 542604974** [comment]
用plus就出现有条黑边这个问题了

**Comment by 542604974** [comment]
我估计是约束的问题

**Comment by keshiim** [comment]
@542604974 真没在plus上调试过，我试了下，确实会闪现一个黑边

**Comment by keshiim** [comment]
@542604974 算了。我自己改吧

**Comment by 542604974** [comment]
那啥时候解决，还有滤镜，这样我就可以用你这个框架了

**Comment by keshiim** [comment]
bug我马上就能fix。but，new feature需要等一哈！
