### ISSUE TITLE
你好,按照你正文的方法添加的 pod 库有 bug

### ISSUE THREAD

**Issue by bnlxl** [keshiim/ZMJImageEditor#5]
里面 TOCrpToolbar.m 文件 25行 @import YYCategories 方法报错,无法使用

**Comment by keshiim** [comment]
你是使用pod引入的吗

**Comment by leozhuo** [comment]
改成#import “YYCategories.h”就行了

**Comment by bnlxl** [comment]
可是pod进来的.团队都在用..要改4份代码..而且等你这边新的功能迭代了..下次pod的时候还会有..

**Comment by keshiim** [comment]
@bnlxl 你好，如果是@import给带去的困扰，我会考虑使用#import
